project:
  type: website

website:
  title: "TKF - Wiki"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    contents: auto

format:
  html:
    grid:
      body-width: 1200px
      margin-width: 200px
      sidebar-width: 400px
    theme: 
      - cosmo
      - custom.scss
    css: 
      - gfont/css/quicksand.css
      - custom.css

editor: visual
