project:
  type: website

website:
  title: "Wiki"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
  sidebar:
    contents: auto

author:
  - name: Philippe PERET
    orcid: 0009-0003-9666-7490

format:
  html:
    grid:
      body-width: 1000px
      margin-width: 250px
      sidebar-width: 300px
    theme: 
      - cosmo
      - custom.scss
    css: 
      - gfont/css/quicksand.css
      - custom.css
    link-external-icon: true
    link-external-newwindow: true

editor: visual
